// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phppkguqvucqvyycemeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBocHBrZ3VxdnVjcXZ5eWNlbWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTA1MzcsImV4cCI6MjA2NTEyNjUzN30.bDugH3_dxFJLvnLc6CCzBEW9MEz25g04u0c5JTjLuzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);